name: CI Github Action
on:
  push:
    branches: [ master ]

jobs:
  build-react:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install dependencies
        run: npm install
      - name: Test Artefact 
        run: npm test
      - name: Build Artefact 
        run: npm run build
      - name: Echo variables
        run: echo ${{ secrets.SECRET_ID }} ${{ secrets.ACCESS_TOKEN }}
      - name: Deploy app
        run: netlify deploy --site ${{ secrets.SECRET_ID }} --auth ${{ secrets.ACCESS_TOKEN }} --dir build/ --prod