name: CI Github Action
on:
  push:
    branches: [ master ]

jobs:
  build-react:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Cache
        uses: actions/cache@v3.0.8
        with:
        path:
        - node_modules
        - package-lock.json
        - build 
      - name: Test Artefact 
        run: npm test
      - name: Echo variable
        run: echo ${{ secrets.SECRET_ID }} ${{ secrets.ACCESS_TOKEN }}
      - name: Deploy app
        run: netlify deploy --site ${{ secrets.SECRET_ID }} --auth ${{ secrets.ACCESS_TOKEN }} --dir build/ --prod